export * as $Named from './$named.js'
export * as $Scalars from './scalars/_.js'

export type * from './_context.js'
export type * from './_document.js'

export type * from './roots/Query/_.js'
export type * from './roots/Mutation/_.js'
export type * from './objects/ActivityLikeNotification/_.js'
export type * from './objects/ActivityMentionNotification/_.js'
export type * from './objects/ActivityMessageNotification/_.js'
export type * from './objects/ActivityReply/_.js'
export type * from './objects/ActivityReplyLikeNotification/_.js'
export type * from './objects/ActivityReplyNotification/_.js'
export type * from './objects/ActivityReplySubscribedNotification/_.js'
export type * from './objects/AiringNotification/_.js'
export type * from './objects/AiringProgression/_.js'
export type * from './objects/AiringSchedule/_.js'
export type * from './objects/AiringScheduleConnection/_.js'
export type * from './objects/AiringScheduleEdge/_.js'
export type * from './objects/AniChartUser/_.js'
export type * from './objects/Character/_.js'
export type * from './objects/CharacterConnection/_.js'
export type * from './objects/CharacterEdge/_.js'
export type * from './objects/CharacterImage/_.js'
export type * from './objects/CharacterName/_.js'
export type * from './objects/CharacterSubmission/_.js'
export type * from './objects/CharacterSubmissionConnection/_.js'
export type * from './objects/CharacterSubmissionEdge/_.js'
export type * from './objects/CharacterSubmissionUpdateNotification/_.js'
export type * from './objects/Deleted/_.js'
export type * from './objects/Favourites/_.js'
export type * from './objects/FollowingNotification/_.js'
export type * from './objects/FormatStats/_.js'
export type * from './objects/FuzzyDate/_.js'
export type * from './objects/GenreStats/_.js'
export type * from './objects/InternalPage/_.js'
export type * from './objects/ListActivity/_.js'
export type * from './objects/ListActivityOption/_.js'
export type * from './objects/ListScoreStats/_.js'
export type * from './objects/Media/_.js'
export type * from './objects/MediaCharacter/_.js'
export type * from './objects/MediaConnection/_.js'
export type * from './objects/MediaCoverImage/_.js'
export type * from './objects/MediaDataChangeNotification/_.js'
export type * from './objects/MediaDeletionNotification/_.js'
export type * from './objects/MediaEdge/_.js'
export type * from './objects/MediaExternalLink/_.js'
export type * from './objects/MediaList/_.js'
export type * from './objects/MediaListCollection/_.js'
export type * from './objects/MediaListGroup/_.js'
export type * from './objects/MediaListOptions/_.js'
export type * from './objects/MediaListTypeOptions/_.js'
export type * from './objects/MediaMergeNotification/_.js'
export type * from './objects/MediaRank/_.js'
export type * from './objects/MediaStats/_.js'
export type * from './objects/MediaStreamingEpisode/_.js'
export type * from './objects/MediaSubmission/_.js'
export type * from './objects/MediaSubmissionComparison/_.js'
export type * from './objects/MediaSubmissionEdge/_.js'
export type * from './objects/MediaSubmissionUpdateNotification/_.js'
export type * from './objects/MediaTag/_.js'
export type * from './objects/MediaTitle/_.js'
export type * from './objects/MediaTrailer/_.js'
export type * from './objects/MediaTrend/_.js'
export type * from './objects/MediaTrendConnection/_.js'
export type * from './objects/MediaTrendEdge/_.js'
export type * from './objects/MessageActivity/_.js'
export type * from './objects/ModAction/_.js'
export type * from './objects/NotificationOption/_.js'
export type * from './objects/Page/_.js'
export type * from './objects/PageInfo/_.js'
export type * from './objects/ParsedMarkdown/_.js'
export type * from './objects/Recommendation/_.js'
export type * from './objects/RecommendationConnection/_.js'
export type * from './objects/RecommendationEdge/_.js'
export type * from './objects/RelatedMediaAdditionNotification/_.js'
export type * from './objects/Report/_.js'
export type * from './objects/Review/_.js'
export type * from './objects/ReviewConnection/_.js'
export type * from './objects/ReviewEdge/_.js'
export type * from './objects/RevisionHistory/_.js'
export type * from './objects/ScoreDistribution/_.js'
export type * from './objects/SiteStatistics/_.js'
export type * from './objects/SiteTrend/_.js'
export type * from './objects/SiteTrendConnection/_.js'
export type * from './objects/SiteTrendEdge/_.js'
export type * from './objects/Staff/_.js'
export type * from './objects/StaffConnection/_.js'
export type * from './objects/StaffEdge/_.js'
export type * from './objects/StaffImage/_.js'
export type * from './objects/StaffName/_.js'
export type * from './objects/StaffRoleType/_.js'
export type * from './objects/StaffStats/_.js'
export type * from './objects/StaffSubmission/_.js'
export type * from './objects/StaffSubmissionUpdateNotification/_.js'
export type * from './objects/StatusDistribution/_.js'
export type * from './objects/Studio/_.js'
export type * from './objects/StudioConnection/_.js'
export type * from './objects/StudioEdge/_.js'
export type * from './objects/StudioStats/_.js'
export type * from './objects/TagStats/_.js'
export type * from './objects/TextActivity/_.js'
export type * from './objects/Thread/_.js'
export type * from './objects/ThreadCategory/_.js'
export type * from './objects/ThreadComment/_.js'
export type * from './objects/ThreadCommentLikeNotification/_.js'
export type * from './objects/ThreadCommentMentionNotification/_.js'
export type * from './objects/ThreadCommentReplyNotification/_.js'
export type * from './objects/ThreadCommentSubscribedNotification/_.js'
export type * from './objects/ThreadLikeNotification/_.js'
export type * from './objects/User/_.js'
export type * from './objects/UserActivityHistory/_.js'
export type * from './objects/UserAvatar/_.js'
export type * from './objects/UserCountryStatistic/_.js'
export type * from './objects/UserFormatStatistic/_.js'
export type * from './objects/UserGenreStatistic/_.js'
export type * from './objects/UserLengthStatistic/_.js'
export type * from './objects/UserModData/_.js'
export type * from './objects/UserOptions/_.js'
export type * from './objects/UserPreviousName/_.js'
export type * from './objects/UserReleaseYearStatistic/_.js'
export type * from './objects/UserScoreStatistic/_.js'
export type * from './objects/UserStaffStatistic/_.js'
export type * from './objects/UserStartYearStatistic/_.js'
export type * from './objects/UserStatistics/_.js'
export type * from './objects/UserStatisticTypes/_.js'
export type * from './objects/UserStats/_.js'
export type * from './objects/UserStatusStatistic/_.js'
export type * from './objects/UserStudioStatistic/_.js'
export type * from './objects/UserTagStatistic/_.js'
export type * from './objects/UserVoiceActorStatistic/_.js'
export type * from './objects/YearStats/_.js'
export type * from './unions/ActivityUnion/_.js'
export type * from './unions/LikeableUnion/_.js'
export type * from './unions/NotificationUnion/_.js'
export type * from './enums/ActivitySort.js'
export type * from './enums/ActivityType.js'
export type * from './enums/AiringSort.js'
export type * from './enums/CharacterRole.js'
export type * from './enums/CharacterSort.js'
export type * from './enums/ExternalLinkMediaType.js'
export type * from './enums/ExternalLinkType.js'
export type * from './enums/LikeableType.js'
export type * from './enums/MediaFormat.js'
export type * from './enums/MediaListSort.js'
export type * from './enums/MediaListStatus.js'
export type * from './enums/MediaRankType.js'
export type * from './enums/MediaRelation.js'
export type * from './enums/MediaSeason.js'
export type * from './enums/MediaSort.js'
export type * from './enums/MediaSource.js'
export type * from './enums/MediaStatus.js'
export type * from './enums/MediaTrendSort.js'
export type * from './enums/MediaType.js'
export type * from './enums/ModActionType.js'
export type * from './enums/ModRole.js'
export type * from './enums/NotificationType.js'
export type * from './enums/RecommendationRating.js'
export type * from './enums/RecommendationSort.js'
export type * from './enums/ReviewRating.js'
export type * from './enums/ReviewSort.js'
export type * from './enums/RevisionHistoryAction.js'
export type * from './enums/ScoreFormat.js'
export type * from './enums/SiteTrendSort.js'
export type * from './enums/StaffLanguage.js'
export type * from './enums/StaffSort.js'
export type * from './enums/StudioSort.js'
export type * from './enums/SubmissionSort.js'
export type * from './enums/SubmissionStatus.js'
export type * from './enums/ThreadCommentSort.js'
export type * from './enums/ThreadSort.js'
export type * from './enums/UserSort.js'
export type * from './enums/UserStaffNameLanguage.js'
export type * from './enums/UserStatisticsSort.js'
export type * from './enums/UserTitleLanguage.js'
export type * from './input-objects/AiringScheduleInput/_.js'
export type * from './input-objects/AniChartHighlightInput/_.js'
export type * from './input-objects/CharacterNameInput/_.js'
export type * from './input-objects/FuzzyDateInput/_.js'
export type * from './input-objects/ListActivityOptionInput/_.js'
export type * from './input-objects/MediaExternalLinkInput/_.js'
export type * from './input-objects/MediaListOptionsInput/_.js'
export type * from './input-objects/MediaTitleInput/_.js'
export type * from './input-objects/NotificationOptionInput/_.js'
export type * from './input-objects/StaffNameInput/_.js'

import type * as $$Utilities from 'graffle/utilities-for-generated'
import type { GraphqlKit } from 'graffle/utilities-for-generated'
import type * as $$Schema from '../schema/_.js'

/**
* Infer the result type of a Query selection set.
*
* Given a selection set object, this type computes the exact TypeScript type
* of the data that will be returned from executing the Query operation.
*/
export type Query$Infer<$SelectionSet extends object> = GraphqlKit.Document.Object.InferResult.OperationQuery<$SelectionSet, $$Schema.Schema>

/**
* Infer the variables type for a Query selection set.
*
* @deprecated This is temporarily typed as `any` and will be replaced with the new analysis system.
*/
export type Query$Variables<_$SelectionSet> = any // Temporarily any - will be replaced with new analysis system

/**
* Infer the result type of a Mutation selection set.
*
* Given a selection set object, this type computes the exact TypeScript type
* of the data that will be returned from executing the Mutation operation.
*/
export type Mutation$Infer<$SelectionSet extends object> = GraphqlKit.Document.Object.InferResult.OperationMutation<$SelectionSet, $$Schema.Schema>

/**
* Infer the variables type for a Mutation selection set.
*
* @deprecated This is temporarily typed as `any` and will be replaced with the new analysis system.
*/
export type Mutation$Variables<_$SelectionSet> = any // Temporarily any - will be replaced with new analysis system
